version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  quiz:
    container_name: question
    restart: on-failure
    build: .
    command: bash -c 'alembic revision --autogenerate -m "First" && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    volumes:
      - './:/quiz'
    depends_on:
      - db

volumes:
  postgres_data: